### ISSUE TITLE
关于thinkpad x1 yoga 2018 hackintosh 使用体验

### ISSUE THREAD

**Issue by ColorYourDream** [Jamesxxx1997/thinkpad-x1-yoga-2018-hackintosh#1]
能否留个联系方式，请教一下使用体验，telegram或其他方式都可以

**Comment by Jamesxxx1997** [comment]
你好，可以
1. 上遠景搜索thinkpad x1 yoga 2018 hackintosh
2. youtube搜尋thinkpad x1 yoga 2018 hackintosh，有我錄製的影片
3. 我的QQ ： 2169114024

**Comment by ColorYourDream** [comment]
> 你好，可以
> 
> 1. 上遠景搜索thinkpad x1 yoga 2018 hackintosh
> 2. youtube搜尋thinkpad x1 yoga 2018 hackintosh，有我錄製的影片
> 3. 我的QQ ： 2169114024

👌 已加
