### ISSUE TITLE
Can't boot Mac OS Mojave installer crash

### ISSUE THREAD

**Issue by 0ctoqus** [Jamesxxx1997/thinkpad-x1-yoga-2018-hackintosh#2]
Hi, I'v tried using the config as is and installing Mojave on my Thinkpad but I keep getting kernel crashs during boot.
It comes from AppleIntelFramebuffer/AppleIntelCrontroller.cpp:28510.
![IMG_0121](https://user-images.githubusercontent.com/42735996/66714288-412f6780-edb5-11e9-82cb-e15423ab0d05.PNG) (Sorry for the blurry pic)
I have looked into the whatevergreen and lilu configuration but I can't seem to get it working.

If you have any idea how to resolve this please, thank you.

My Thinkpad is a X1 Yoga 3rd gen 20LE.

**Comment by Jamesxxx1997** [comment]
Sorry , I've no ability to solve problem like this.
Hope you open a thread or ask your question in tonymacx86 and find out the solution.
